### ISSUE TITLE
different from official document

### ISSUE THREAD

**Issue by maxisam** [shawnwildermuth/DualAuthCore#2]
in the document here 
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#cookie-based-authentication

When using cookie with .net core identity

> Invoke the AddIdentity method in the ConfigureServices method to add the cookie authentication services.

But the way you do is different.

Could you explain the difference? Thx

**Comment by shawnwildermuth** [comment]
Because i'm using two different auth types, we need to configure them separately. If you just call AddIdentity you're getting cookie by default, but I need cookie and JWT.

**Comment by maxisam** [comment]
Well, how about call addIdentity and AddJwtBearer? I tried it and it seems like it works too.

**Comment by maxisam** [comment]
FYI, in my case, it seems like I need to add the following code to make jwt work

using Microsoft.AspNetCore.Authentication.JwtBearer;

services.AddAuthentication((options) =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
