### ISSUE TITLE
.Net Core 3

### ISSUE THREAD

**Issue by gvsrini** [shawnwildermuth/DualAuthCore#3]
Could you update this for ASP.Net Core 3. Seems to be broken again. What used to work for me in .Net core 2.2 doesn't work in .Net Core 3.

**Comment by shawnwildermuth** [comment]
I'll try but probably not until 3.0 releases. YOu could send me a PR if you have a fix.

**Comment by shawnwildermuth** [comment]
Sorry, I'm updated to 3.1 now.
