### ISSUE TITLE
Problem in create Register page asp.net core 3.1

### ISSUE THREAD

**Issue by tarek4489** [shawnwildermuth/DualAuthCore#7]
The error

![wer](https://user-images.githubusercontent.com/57232052/90302949-413e3f00-de80-11ea-9edd-f048df7fd628.jpg)

The    code

public class SetorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationDbContext context;

        public SetorsController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // GET: Admin/Setors
        [HttpGet]
        public async Task<IActionResult> Cadastrar()
        {
            RegisterViewModel model = new RegisterViewModel()
            {
                SetoresList = await context.Setores.ToListAsync(),
                UnidadesList = await context.Unidades.ToListAsync()
            };

            return View();
        }

        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public SetorsController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        private RegisterViewModel RegisterViewModel()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastrar(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = model.Email, Email = model.Email };
                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

**Comment by shawnwildermuth** [comment]
Get new source, should be fixed now.
